giampaolo/psutil

psutil/_common.py
psutil/_psutil_windows.c
psutil/arch/windows/ntextapi.h
psutil/arch/windows/process_handles.c
psutil/arch/windows/process_info.h
setup.py
test/_windows.py
test/test_psutil.py

also silence most compilation warnings

fix most warnings and test failures on win32

---

CREDITS
HISTORY.rst
psutil/_pssunos.py
test/_sunos.py

This is a bit of a kludge, but allows to find the swap utility when
invoced by normal users which shouldn't have the sbin paths in PATH by
default.  One can argue the paths should be appended instead of
prepended, but I doubt whether one wants to use another swap utility,
since the code relies on its output format.
Fixes issue #618.

swap: fix finding the 'swap' utility on SunOS

---

CREDITS
HISTORY.rst
psutil/_psutil_sunos.c

During kstat enumeration in net_io_counters on Solaris, we check for class=net and module=link to find kstats for network interfaces. As reported in #517 (example kstat output is submitted there), module is not always 'link' so on Solaris 10 we don't find any interfaces.
net_if_stats does the same enumeration but there is no problem there because it doesn't check the module, and instead sends a ioctl and decides if the current stat name is a network interface name according to the result. I copied the same logic from there to net_io_counters.
Also fixed 2 minor bugs along the way that would only happen in error cases.
The second commit is modelled after parts of the patch in #517 but also fixes the data types passed to Py_BuildValue.

Fix #517 (net_io_counters on Solaris 10)

---

psutil/_psutil_bsd.c

In FreeBSD version of disk_io_counters read/write times are returned in seconds, not in milliseconds, as it is stated in the documentation.

Fix freebsd disk io counters

---

psutil/arch/bsd/freebsd.c

Its type is 'unsigned long', not 'unsigned int'. Passing wrong type
variable causes returning ENOMEM.
Type definition is [here](https://svnweb.freebsd.org/base/release/10.2.0/sys/kern/kern_mib.c?view=markup#l175)
This is related to #730.

Correct data type for 'hw.physmem'

---

psutil/_psutil_windows.c
test/_windows.py

Saw this compiler warning popping up and thought I could take a look:
```
psutil/_psutil_windows.c(2081) : warning C4133: 'function' : incompatible types - from 'PyObject *' to 'const char *'
```

fix net_if_stats on Windows wip

---

CREDITS
HISTORY.rst
psutil/_psutil_windows.c
psutil/tests/test_posix.py

I am updating this with a new pull request. The other one was very old and didn't quite work with the current version of psutil. See more #816

[Windows] Fix for net_io_counters wrapping after 4.3GB due to MIB_IFROW

---

CREDITS
HISTORY.rst
psutil/_psutil_windows.c

We've been getting rather frequent cases where the `psutil.Process().connections()` returns an empty list on Windows when we know for a fact that there are open TCP connections on the machine.
We traced down the problem to the fact that there is a race condition in the `GetExtendedTCPTable()` API: since we call it twice (once to get the size, once to read the data), it happends that new connections open between the two calls to the `GetExtendedTCPTable()` function and the table size is too small on the 2nd call.
The solution to this is to call the function in a loop and repeat until we manage to successfully read the data.
I couldn't run the tests on my machine, so I'm sending this as a preliminary patch.   I think the other calls (e.g. for IPv6, and probably UDP) also need this too. …

Fixes race condition getting IPv4 TCP table on Windows.

---

psutil/__init__.py

This fixes exception pickling. The error can be reproduced with the following code:
```python
>>> import pickle
>>> import psutil
>>>
>>> pkexc = pickle.dumps(psutil.NoSuchProcess(123))
>>> e = pickle.loads(pkexc)
Traceback (most recent call last):
...
TypeError: __init__() takes at least 2 arguments (1 given)
```
Calling the base class constructor fixed it.

Allow exception pickling.

---

psutil/_psutil_linux.c

Suppress inclusion of linux/sysinfo.h to fix redefinition of struct sysinfo
that musl libc defines in sys/sysinfo.h, which least to the following build
failure (paths abbreviated):
In file included from .../usr/include/linux/kernel.h:4:0,
from .../usr/include/linux/ethtool.h:16,
from psutil/_psutil_linux.c:35:
.../usr/include/linux/sysinfo.h:7:8: error: redefinition of ‘struct sysinfo’
struct sysinfo {
^
In file included from psutil/_psutil_linux.c:21:0:
.../usr/include/sys/sysinfo.h:10:8: note: originally defined here
struct sysinfo {
^
Fixes #872

Fix build with musl libc

---

psutil/arch/bsd/freebsd_socks.c

This file was derived from FreeBSD usr.bin/sockstat/sockstat.c. The
logic of socket to PID translation was copied incorrectly. The hash,
that sockstat(1) utility has, is completely internal feature, it isn't
part of FreeBSD API, it is just to speed things up. So, to use this
hash one actually needs to create it: declare array of buckets, populate
it with sockets. In the freebsd_socks.c this wasn't done. This fix
doesn't create the hash, instead it removes remnants of hashing that was
there in sockstat.c. It makes code more simple, but of course slower than
original sockstat(1) in case if machine is running zillions of sockets. I
decided to go this way simply because I am low on time to invest into
psutil, and also because better first provide correct and simple
implementation and then …

Fix socket to PID translation on FreeBSD.

---

CREDITS
HISTORY.rst
psutil/_psutil_sunos.c

Addresses were truncated at least on LP64

SunOS: Fix .memory_maps(grouped=False)

---

psutil/_psutil_windows.c
psutil/arch/windows/process_info.c
psutil/arch/windows/process_info.h
psutil/tests/__init__.py

So this is kind of a big one and the repercussions are hard to describe because it's subtle. This test case:
https://github.com/giampaolo/psutil/blob/cee414dca663bdac9712c0779e43ce0c184e904e/psutil/tests/__init__.py#L387-L399
...which was disabled on Windows, shows that processes unexpectedly stick around after being `terminate()`ed and `wait()` on. The problem originates from `OpenProcess()` Windows API. 
`OpenProcess()` is unreliable in that it can return a handle for a process PID which no longer exists, so we assumed that `GetExitCodeProcess` returning `STILL_ACTIVE` meant it was running, else it wasn't. It turns this is not always the case. This had repercussions on `psutil.pid_exists()` API which returned an incorrect value, and also on other psutil APIs relying on it internally …

Windows: fix wrapper around OpenProcess (pid_exists() no longer lies)

---

psutil/_psutil_sunos.c

Fix some compilation warnings on Solaris.
Output of `python setup.py develop` prior to fixes:
running develop
running egg_info
writing requirements to psutil.egg-info/requires.txt
writing psutil.egg-info/PKG-INFO
writing top-level names to psutil.egg-info/top_level.txt
writing dependency_links to psutil.egg-info/dependency_links.txt
reading manifest file 'psutil.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'psutil.egg-info/SOURCES.txt'
running build_ext
building 'psutil._psutil_sunos' extension
gcc -fno-strict-aliasing -I/root/python/include -m64 -I/root/python/include/gnutls -I/root/python/include/graphviz -I/root/python/include/libexslt -I/root/python/include/libxml2 -I/root/python/include/libxslt -I/root/python/include/ncurses …

Solaris: fix compilation warnings

---

psutil/_psutil_posix.c

referred by https://bugzilla.redhat.com/attachment.cgi?id=150888&action=diff .

Fix #1138:  error on CentOS 5.0: expected specifier-qualifier-list before ‘__u3

---

psutil/TODO.aix
psutil/_psaix.py

The 'kill' method to check whether processes exist doesn't work on 'wait' processes in AIX. All processes (and only processes) have a "psinfo" file in procfs so we can check whether PIDs exist there.

Fix #1136: check PID in AIX in procfs

---

.git-pre-commit

This error prevents committing when the system python is 3.x, such as on Arch Linux.
Traceback (most recent call last):
File ".git/hooks/pre-commit", line 118, in <module>
main()
File ".git/hooks/pre-commit", line 78, in main
py_files = [x for x in out.split(b'\n') if x.endswith(b'.py') and
TypeError: must be str or None, not bytes
sh() return value is a string due to Popen(universal_newlines=True).

Fix pre-commit hook for python 3.x.

---

psutil/tests/test_connections.py
psutil/tests/test_unicode.py

Two cases where a test subprocess is not cleaned up after the test, leading to asserts in following tests.

Fix test asserts due to leftover test subprocesses

---

psutil/__init__.py
psutil/_exceptions.py
psutil/_psaix.py
psutil/_psbsd.py
psutil/_pslinux.py
psutil/_psosx.py
psutil/_pssunos.py
psutil/_pswindows.py

I'm not sure if there was a reason that the exceptions are not in a separate file. It looks simpler to import them instead of defining them as "None" in the platform modules and then overriding them from the main file, plus it cleans up the main file a bit.

Move exceptions to separate file

---

docs/index.rst

Typo fix. Prevents `NameError: name 'batt' is not defined`.

docs: fix battery variable

---

psutil/_psbsd.py
psutil/_psutil_bsd.c
psutil/arch/freebsd/specific.c
psutil/arch/freebsd/specific.h
psutil/tests/test_bsd.py
psutil/tests/test_contracts.py

This adds support for CPU frequency on FreeBSD. (Addresses #1352)
An example `sysctl` call looks like this:
```
dev.cpu.0.freq_levels: 2701/45000 2700/45000 2600/42708 2500/40461 2400/38257 2300/36525 2200/34401 2100/32327 1900/28698 1800/26736 1700/24815 1600/23334 1500/21489 1400/19683 1300/18298 1200/16566
dev.cpu.0.freq: 1200
```
Frequency reading is only available for core 0, as explained here: https://stackoverflow.com/questions/9941664/how-to-get-real-cpu-frequency-while-system-running
The available frequency levels are in the format `(frequency/power usage)` (as per https://www.unix.com/man-page/FreeBSD/4/cpufreq/). 
To my knowledge, in this example the top frequency level is `2701`, and the one after it is `2700`. The `1` indicates that _Turbo_ frequency is enabled, but I do not …

Add CPU frequency support for FreeBSD

---

psutil/_psutil_windows.c
psutil/tests/__init__.py

- `Process().ionice(0/1/2)` does not work on windows x64 due to `sizeof((PVOID)prio)` being used as size.
This is 4 on 32bits, and 8 on 64 bits. On 64 bits, an error **0xC0000004** is returned (STATUS_INFO_LENGTH_MISMATCH)
- fix a typo in **psutil_proc_io_priority_get** where a prio is defined as `PULONG` instad of `DWORD` 
- request only `PROCESS_SET_INFORMATION | PROCESS_QUERY_INFORMATION `rights when opening a process for changing its I/O priority (instead of `ALL_ACCESS` which is way too much for this operation)
- fix travis-ci check on python 3.6 (tests/__init__.py:638:17: F841 local variable '_' is assigned to but never used")
how to reproduce ionice bug (tested on python 3.6.7 on win 7 x64): 
```
>>> import psutil
>>> a=psutil.Process()
>>> a.ionice()
2
>>> a.ionice(1)
>>> …
```

fix ionice set not working on windows x64 due to LENGTH_MISMATCH 

---

psutil/arch/aix/net_kernel_structs.h

Fix #1408: add missing header that defines m_len on AIX 64-bit mode

---

HISTORY.rst
psutil/__init__.py
psutil/_psutil_windows.c
psutil/_pswindows.py

#1394 / win / exe: use QueryFullProcessImageNameW to get the exe()

---

make.bat
psutil/_psutil_windows.c
psutil/arch/windows/inet_ntop.h
psutil/arch/windows/process_handles.c
psutil/arch/windows/process_info.c
psutil/arch/windows/process_info.h

Move the logic in a single place and reuse it.

Windows / refactoring: utility functions for LoadLibraryA and GetProcAddress

---

Makefile
psutil/_psutil_windows.c
psutil/arch/windows/security.c
psutil/arch/windows/security.h
scripts/internal/procs_access_denied.py
scripts/internal/winmake.py

From the code:
```c
/*
* Set this process in SE DEBUG mode so that we have more chances of
* querying processes owned by other users, including many owned by
* Administrator and Local System.
* https://docs.microsoft.com/windows-hardware/drivers/debugger/debug-privilege
*/
```
^ that is what we are supposed to do on module import. While I was refactoring this function I realized that the code which uses it never checks return code/error, so ~~possibly~~ SE DEBUG has never been set ~~(or it has been broken at some point, I wouldn't know)~~. Now it's set and will raise exception on import in case of error (not what I want - will change it later). Perhaps this means we're now gonna get less AccessDenied exceptions for PIDs owned by other/system users? 
@jloden - you wrote this code 10 years …

Process SE DEBUG mode is not set on Windows

---

psutil/_psaix.py
psutil/_psutil_aix.c
psutil/tests/__init__.py
psutil/tests/test_contracts.py
psutil/tests/test_memory_leaks.py
psutil/tests/test_misc.py
psutil/tests/test_posix.py
psutil/tests/test_system.py

Fix #1329: [AIX] disable some functions based on availability in libperfstat

---

CREDITS
HISTORY.rst
docs/DEVGUIDE.rst
docs/index.rst
psutil/__init__.py
psutil/tests/runner.py

* use https wherever possible
* always point to python 3 doc
* point to new MSDN urls
* use RST references and avoid repetitions of URLs

Big docfix

---

.gitignore
psutil/_pslinux.py
psutil/tests/test_linux.py

This PR addresses issue #1472.
`cpu_freq()` is updated to to check whether `/sys/devices/system/cpu/cpufreq/policy*` or `/sys/devices/system/cpu/cpu*/cpufreq` exists.
Tests updated to test for both cases and for multiple CPUs

Cpu freq fix

---

CREDITS
HISTORY.rst
psutil/_pslinux.py
psutil/tests/test_linux.py

This PR fixes issue #1456
Return 0.0 for cpu_freq min and max values if not available.

Update cpu_freq to return 0 for max/min if not available

---

psutil/_pslinux.py

/proc/meminfo usually has a space after the field name, but not always.  This is a (buggy) output from WSL showing 16EB of swap free.
```bash
$ cat /proc/meminfo
MemTotal:       16653648 kB
MemFree:          891564 kB
Buffers:           34032 kB
Cached:           188576 kB
SwapCached:            0 kB
Active:           167556 kB
Inactive:         157876 kB
Active(anon):     103104 kB
Inactive(anon):    17440 kB
Active(file):      64452 kB
Inactive(file):   140436 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      22806844 kB
SwapFree:18014398503714728 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        102824 kB
Mapped:            71404 kB
Shmem:             17720 kB
Slab:              13868 kB
SReclaimable:       6744 kB
SUnreclaim: …
```

Add handling of missing space in meminfo output

---

HISTORY.rst
psutil/_psbsd.py
psutil/arch/netbsd/specific.c

...from C we get EINVAL, which is then (erroneously) turned into ZombieProcess since the PID is still alive. Instead return an empty list. This was exercised by (invalid chars) unicode tests.

[NetBSD] cmdline() raise ZombieProcess when unable to decode chars

---

scripts/internal/print_timeline.py

with -> out = sh("git tags"):
git: 'tags' is not a git command. See 'git --help'.
with -> out = sh("git tag"):
- 2019-06-11:
`5.6.3 <https://pypi.org/project/psutil/#files>`__ -
`what's new <https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#563>`__ -
`diff <https://github.com/giampaolo/psutil/compare/release-5.6.2...release-5.6.3#files_bucket>`__
...
...
...

typo fix scripts/internal/print_timeline.py

---

docs/index.rst

Terminate my children example had some errors:
```
log("process {} survived SIGTERM; trying SIGKILL" % p)
TypeError: not all arguments converted during string formatting
```
https://psutil.readthedocs.io/en/latest/index.html#terminate-my-children

docs: fix TypeError in example

---

psutil/_psutil_aix.c
psutil/_psutil_bsd.c
psutil/_psutil_linux.c
psutil/_psutil_osx.c
psutil/_psutil_sunos.c
psutil/_psutil_windows.c

These files contain loops that convert system data into python objects
and during the process they create objects and dereference their
refcounts after they have been added to the resulting list.
However, in case of errors during the creation of those python objects,
the refcount to previously allocated objects is dropped again with
Py_XDECREF, which should be a no-op in case the paramater is NULL. Even
so, in most of these loops the variables pointing to the objects are
never set to NULL, even after Py_DECREF is called at the end of the loop
iteration. This means, after the first iteration, if an error occurs
those python objects will get their refcount dropped two times,
resulting in a possible double-free.
In any case, making functions like PyUnicode_DecodeFSDefault fail does not seem …

Use Py_CLEAR instead of Py_DECREF to also set the variable to NULL

---

CREDITS
HISTORY.rst
psutil/_psutil_sunos.c
psutil/arch/solaris/environ.c
setup.py

This add support for SunOS 5.10 update prior to 4.
It shouldn't change anything for conforming targets but add support for older targets.

[Solaris] Fix #1637

---

psutil/_pslinux.py

Kernel 5.5 added 2 more fields to /proc/diskstats, requiring another
change after the one for 4.18, which recently added 4 fields.
At this point in time, the meaning of the existing fields is unlikely to
change, and psutil is not using any of the newer ones. By considering
18 fields and more to have the current layout, psutil will continue to
work as newer kernels add more fields.

Future-proof disk_ui_counters on Linux.

---

HISTORY.rst
psutil/_pslinux.py
psutil/tests/test_linux.py

Fixes:
```
======================================================================
ERROR: psutil.tests.test_linux.TestSystemDiskIoCounters.test_emulate_use_sysfs
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/giampaolo/svn/psutil/psutil/tests/test_linux.py", line 1195, in test_emulate_use_sysfs
wsysfs = psutil.disk_io_counters(perdisk=True)
File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 2065, in disk_io_counters
rawdict = _psplatform.disk_io_counters(**kwargs)
File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1124, in disk_io_counters
for entry in gen:
File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1110, in read_sysfs
wbytes, wtime, _, busy_time, _) = map(int, fields)
ValueError: too …
```

[Linux] disk_io_counters() ValueError when parsing /sys/block

---

psutil/_pslinux.py

/proc/cpuinfo uses spaces rather than tabs on ia64.  Since there seems
not to be any reason to require specific kind of whitespace before ':'
on 'cpu mhz' line, just split on ':'.
See: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/ia64/kernel/setup.c#n700

Fix handling /proc/cpuinfo without tabs

---

psutil/tests/__init__.py
psutil/tests/runner.py
psutil/tests/test_bsd.py
psutil/tests/test_connections.py
psutil/tests/test_linux.py
psutil/tests/test_osx.py
psutil/tests/test_posix.py
psutil/tests/test_process.py
psutil/tests/test_system.py
psutil/tests/test_testutils.py
psutil/tests/test_unicode.py
psutil/tests/test_windows.py

Thus far test processes (`psutil.tests.get_test_subprocess()`) were created and cleaned up every once in a while (typically in `tearDown`) instead of on a per-test basis. That's because `get_test_subprocess()` relies on a global list where the instances are stored and are cleanup up via `psutil.tests.reap_children()`. 
This PR introduces a `ProcessTestCase` class which provides utility wrappers on top of `get_test_subprocess()` and others, and terminate/wait/cleanup subprocesses after each individual unit-test completes. Hopefully this should fix some (very) occasional failures due to orphaned subprocesses sticking around and interfering with `Process.children()` tests.

Test sub-processes cleanup and ProcessTestCase class

---

docs/index.rst

Changed system_user to children_system to match the named tupple and expected behaviour.

Fix labeling in Process cpu_times() documentation

---

HISTORY.rst
README.rst
docs/index.rst
psutil/__init__.py
psutil/_common.py
psutil/_psaix.py
psutil/_psbsd.py
psutil/_pslinux.py
psutil/_psosx.py
psutil/_pssunos.py
psutil/_psutil_bsd.c
psutil/arch/freebsd/specific.c
psutil/arch/windows/disk.c
psutil/tests/test_contracts.py
psutil/tests/test_system.py
scripts/internal/download_wheels_appveyor.py

Adds `maxfile` and `maxpath` fields to the namedtuple returned by `psutil.disk_partitions()`. See: https://github.com/giampaolo/psutil/issues/1857.

disk_partitions() maxfile and maxpath 

---

CREDITS
HISTORY.rst
psutil/_pssunos.py

Updated to grab the columns based on row location to fix #1874

Fix solaris swap output when 'encrypted' column exists

---

psutil/_psaix.py
psutil/_psbsd.py
psutil/_pslinux.py
psutil/_psosx.py
psutil/_pssunos.py
psutil/_psutil_aix.c
psutil/_psutil_bsd.c
psutil/_psutil_osx.c
psutil/_psutil_posix.c
psutil/_psutil_posix.h
psutil/arch/freebsd/specific.c
psutil/arch/netbsd/specific.c
psutil/arch/openbsd/specific.c
psutil/tests/test_bsd.py
psutil/tests/test_osx.py
psutil/tests/test_posix.py
psutil/tests/test_system.py

* OS: macOS, UNIX
* Bug fix: yes
* Type: core
* Fixes: #1885
Add a reusable `psutil_getpagesize()` utility common to all UNIXes.
Related to #1885 (`getpagesize()` is deprecated on recent macOS, POSIX.1-2001 and possibly other UNIXes).
The problem emerged on macOS but `getpagesize()` is also used in FreeBSD, NetBSD, OpenBSD and AIX, so it makes sense to do this in one place only, similarly to Windows which also provide a `psutil_getpagesize()` utility.
Follow cPython's `mmapmodule.c` and `resourcemodule.c` lead and rely on `sysconf(_SC_PAGESIZE)` instead, but leave `getpagesize()` in place as last resort/attempt for systems where it's not deprecated and/or they still legitimately rely on it.
Also provide a python wrapper so we can test the return value of this C function against Python's …

[macOS, UNIX] prefer _SC_PAGESIZE over (partially) deprecated getpagesize()

---

HISTORY.rst
psutil/_pssunos.py

* OS: Solaris
* Bug fix: yes
* Type: core
* Fixes: Typo in the range for swap output
Not sure how I missed this in the issue, but when I submitted the PR the range was not both columns, just one column. Updated to 3:5 instead of 3:4 to grab both blocks and free columns.

Fix incorrect range for Solaris swap output (#1874)

---

HISTORY.rst
psutil/_common.py
psutil/_pslinux.py

* OS: Linux
* Bug fix: yes
* Type: core
* Fixes: 2050
Increase `read(2)` buffer size from 1k to 32k when reading `/proc` pseudo files line by line. This should help having more consistent results.

[Linux]: increase `read(2)` buffer size when reading /proc files lines

---

Makefile
psutil/__init__.py
psutil/tests/__init__.py
psutil/tests/test_system.py

* OS: OpenBSD, NetBSD
* Bug fix: yes
* Type: core
* Fixes: 
* #2287
* 
Zombie processes on Open/NetBSD have a creation time of 0.0. Modify `__eq__` so that it takes this into account, fixing `is_running()` return False for a process which turned into a zombie.

[OpenBSD, NetBSD] fix zombie process with no ctime

---

HISTORY.rst
psutil/_psbsd.py
psutil/arch/netbsd/socks.c

* OS: NetBSD
* Bug fix: no
* Type: core, performance
Modify `psutil.net_connections()` to retrieving unnecessary connection types unless explicitly asked. E.g., on an IDLE system with few IPv6 connections this will run around 170% faster:
```python
import psutil, time
started = time.monotonic()
for x in range(1000):
psutil.net_connections("tcp6")
print(f"completed in {(time.monotonic() - started):.4f} secs")
```
Before all connection types (TCP, UDP, UNIX) were retrived internally, even if they were not returned.

[NetBSD] speedup net_connections() with proper filtering in C

---

HISTORY.rst
psutil/_psbsd.py
psutil/arch/freebsd/sys_socks.c

* OS: FreeBSD
* Bug fix: no
* Type: core, performance
Modify `psutil.net_connections()` to retrieving unnecessary connection types unless explicitly asked. E.g., on an IDLE system with few IPv6 connections this will run around 4 times faster:
```python
import psutil, time
started = time.monotonic()
for x in range(1000):
psutil.net_connections("tcp6")
print(f"completed in {(time.monotonic() - started):.4f} secs")
```
Before all connection types (TCP, UDP, UNIX) were retrieved internally, even if only a portion was returned.

[FreeBSD] speed up net_connections()

---

HISTORY.rst
psutil/_psbsd.py
psutil/tests/test_process_all.py

* OS: OpenBSD
* Bug fix: yes
* Type: core
This is sort of similar to https://github.com/giampaolo/psutil/pull/2394 on Windows. `pid_exists()` on OpenBSD returns True if the argument is a thread ID (TID) instead of a PID (process ID). This is inconsistent with other platforms.

OpenBSD: pid_exists() returns True for thread IDs (TIDs)

---

HISTORY.rst
docs/index.rst
psutil/__init__.py
psutil/tests/test_process.py
psutil/tests/test_system.py

* OS: all
* Bug fix: no
* Type: performance, new-api
* Fixes: 2396
No longer make `process_iter()` check whether PID has been reused. This makes it around 20x times faster on Linux. Also changed `Process.is_running()` so that it will automatically remove the reused PID from `process_iter()` internal cache. In addition, also add a new `process_iter.cache_clear()` API.

Speedup process iter

---

HISTORY.rst
Makefile
psutil/tests/__init__.py
psutil/tests/test_aix.py
psutil/tests/test_bsd.py
psutil/tests/test_connections.py
psutil/tests/test_contracts.py
psutil/tests/test_linux.py
psutil/tests/test_misc.py
psutil/tests/test_osx.py
psutil/tests/test_posix.py
psutil/tests/test_process.py
psutil/tests/test_process_all.py
psutil/tests/test_sunos.py
psutil/tests/test_system.py
psutil/tests/test_testutils.py
psutil/tests/test_unicode.py
psutil/tests/test_windows.py

* Bug fix: no
* Type: tests
* Fixes: 2446
This is a follow up of https://github.com/giampaolo/psutil/pull/2447. In there we changed the runner. In here we get rid of unittest's `self.assert*` APIs and use the bare `assert` keyword instead.

Use pytest, use bare `assert` statements

---

HISTORY.rst
psutil/__init__.py

* OS: all
* Bug fix: yes
* Type: core
* Fixes: #2533

Remove wrong PID reuse assumption in Process `children()` and `parent()`

---

HISTORY.rst
psutil/__init__.py
psutil/tests/test_process.py

* OS: all
* Bug fix: yes
* Type: core
* Fixes: #2542
Fixes https://github.com/giampaolo/psutil/issues/2542.

Make `children()` and `parent()` aware of system clock updates

---

Makefile
psutil/_psutil_common.c
psutil/_psutil_windows.c
psutil/_pswindows.py
psutil/arch/windows/ntextapi.h
psutil/arch/windows/sys.c
psutil/arch/windows/sys.h
psutil/tests/test_sudo.py
psutil/tests/test_windows.py
scripts/internal/winmake.py
setup.py

* OS: Windows
* Bug fix: yes
* Type: core
* Fixes: #2552
On Windows 7+ use `QueryInterruptTime()` instead of `GetTickCount64`. Reason: `QueryInterruptTime()` takes into account the time spent during suspend / hybernate.

[Windows] use `QueryInterruptTime` to determine `boot_time()` 
